### ISSUE TITLE
Ошибки в Разделе 1

### ISSUE THREAD

**Issue by Mila18-star** [pyshkovni/python-base-course#1]
Раздел 1. 
Функции. Свойства и параметры функций. 

Создание и вызов функции 

Цитата:
Обратите внимание, что созданные нами функции являются таким же (должно быть ТАКИМИ ЖЕ), как и встроенные print(), round(), tyре() и др. с одном (должно быть ОДНИМ) только отличием, что встроенные функции хранятся внутри Python
![Screenshot_20241208_195020_Chrome](https://github.com/user-attachments/assets/6a9e1170-2cce-42ee-965c-382b1b3c601b)

**Comment by Mila18-star** [comment]
Раздел 1.
Функции. Свойства и параметры функции.

Имена функций.

Тогда функция должна содержать в указание (должно быть БЕЗ В) на действие и то над чем, это действие совершается.

Решение задачи №3 в виде функции.

Теперь запишем решение задачи внутри функции. Обратите внимание, что внутри функции
действует аргумент staff, которые (должно быть КОТОРЫЙ) обозначает обрабатываемый словарь. 
![Screenshot_20241208_195916_Chrome](https://github.com/user-attachments/assets/c198f19e-edf0-4dac-aab6-aa842e9c088d)

**Comment by Mila18-star** [comment]
Раздел 1.
Функции. Свойства и параметры функции.

Распаковка и запаковка параметров.

Создадим произвольную функцию print_them_all(), которая будет выводит (должно быть ВЫВОДИТЬ) в консоль все 
![Screenshot_20241208_204028_Chrome](https://github.com/user-attachments/assets/5d3e9ea9-d355-4304-90fc-470f7784c691)
запакованные параметры.

**Comment by Mila18-star** [comment]
Раздел 1.
Функции. Свойства и параметры функции.

Документирование и аннотация функции.

Существуют правила как документация в функции должна быть оформлена. Sphinx -это
инструмент для создания документации на языке Руthоn, который поддерживает автоматическое создание документации из соответствующее (должно быть СООТВЕТСТВУЮЩЕГО) блока внутри функции. 

![Screenshot_20241208_205201_Chrome](https://github.com/user-attachments/assets/e20b718b-f0cc-4ba4-9d3b-92bd0e5de754)

**Comment by Mila18-star** [comment]
Раздел 1.
Функции. Свойства и параметры функции.

Документирование и аннотация функции.

Можно конкретизировать тип данных для параметра а. Не смотря (должно быть слитно НЕСМОТРЯ) на синтаксическую ошибку, код будет работать. Более того, функция будет вызвана, даже если передать параметр с другим типом 
![Screenshot_20241208_205733_Chrome](https://github.com/user-attachments/assets/e3c1cc5c-d0f5-46e0-b49e-076f2a616a2b)
данных.

**Comment by Mila18-star** [comment]
Раздел 1.
Функции. Свойства параметров и функции.

Функции документирования и аннотирования.

Следует относится (должно быть ОТНОСИТЬСЯ) к аннотации как к удобной подсказке для программиста. К сожалению возможности оградить функцию от использования неправильных параметров в Руthоn нельзя. К тому же, косвенно об этого (должно быть ЭТОМ) гласит Дзен Python.
![Screenshot_20241208_205841_Chrome](https://github.com/user-attachments/assets/6bee261b-4d2d-48d7-87f6-c469965a39f8)

**Comment by pyshkovni** [comment]
Исправил ошибки! Благодарю!
